---
- name: 'Basic setup | Provision Amadla Image'
  hosts: all
  any_errors_fatal: true # stop if anything is wrong
  gather_facts: true
  become: true # Means become `root` if set with true
  become_user: root
  become_method: sudo
  vars:
    user_username: "{{ lookup('env','USER_USERNAME') }}"
    user_server_password: "{{ lookup('env','USER_SERVER_PASSWORD') }}"
  collections:
    - devsec.hardening
  tasks:

    # Asserts (fail fast)
    #| awk '{ print ($1 == "debian") ? $1 : "" }'

    #- name: Test
    #  shell: cat /etc/os-release
    #  register: result
    #- debug: var=result

    - name: Get OS Release ID
      shell: cat /etc/os-release | grep ID=
      register: result
    - debug: var=result

    - name: Get OS Release Version
      shell: cat /etc/os-release | grep VERSION_ID=
      register: result
    - debug: var=result

    - name: Test5 (so to keep track in case issues arrise)
      shell: uname -r
      register: result_five
    - debug: var=result_five

    #- name: Update all packages on Rocky Linux
    #  become: true
    #  yum:
    #    name: '*'
    #    state: latest- name: Update packages
    
    - name: Update all packages on Rocky Linux
      become: true
      yum:
        name: '*'
        state: latest

    - name: Test6
      shell: cat /etc/selinux/config
      register: result_six
    - debug: var=result_six

    - name: Test7
      shell: sestatus
      register: result_seven
    - debug: var=result_seven

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    #- name: Add `amadla` user
    #  user:
    #    name: "{{ user_username }}"
    #    comment: User creation
    #    shell: /bin/bash
    #    password: "{{ user_server_password | password_hash('sha512') }}"
    #    groups: sudo
    #    append: yes
    #    #update_password: on_create # Only change the password when creating the user (should not be used)

    - name: Create the `.amadla` directory for the settings files
      file:
        path: "/home/{{ lookup('env','USER_USERNAME') }}/.amadla"
        state: directory
        mode: '0755'

    - name: Create the `.amadla/secrets` directory for the settings files
      file:
        path: "/home/{{ lookup('env','USER_USERNAME') }}/.amadla/secrets"
        state: directory
        mode: '0755'

    - name: Add `.ssh` directory
      file:
        path: "/home/{{ lookup('env','USER_USERNAME') }}/.ssh/"
        state: directory
        mode: '0755'
    
    #@TODO Change `root`
    # Adding public SSH key so user and utils can connect to the new server
    - name: Add ssh public key to authorized_keys of the user goin
      shell: "echo \"$(</root/.amadla/secrets/id_rsa.pub)\" >> /home/{{ lookup('env','USER_USERNAME') }}/.ssh/authorized_keys"
      args:
        executable: /bin/bash
      register: resulttwo
      #ignore_errors: True
    - debug: var=resulttwo

    # 
    # Note: OpenSSH 6.8 changed the default fingerprint format from hex MD5 to base64 SHA256.
    #
    # To test Key: $ ansible web -a "ssh-add -l" (p.371-372 (the box thing))
    #
    #- name: Copy known hosts file
    #  copy: src=config/known_hosts dest="/home/{{ lookup('env','USER_USERNAME') }}/.ssh/known_hosts" mode=0600

    # Hardening

    #- name: List all collections
    #  command: ansible-galaxy collection list | grep -E '^[a-zA-Z\.\_0-9]+[ ]+[0-9\.]+' | awk '{ print $1 }'
    #  register: collections
#
    #- set_fact:
    #    collection_list: "{{ collections.stdout_lines }}"
#
    #- name: Update all collections
    #  command: ansible-galaxy collection install {{ item }} --force
    #  with_items: "{{ collection_list }}"
#
    - import_role:
        name: os_hardening

    #- import_role:
    #    name: ssh_hardening 